site_name: "Pulsefire"
repo_url: "https://github.com/iann838/pulsefire"
site_description: "A modern and flexible Riot Games Python SDK."
site_author: "Jian Huang"

theme:
  name: "material"
  logo: logo.svg
  palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

nav:
  - Home: index.md
  - Usage:
    - Basic:
      - Installation: usage/basic/installation.md
      - Quick Start: usage/basic/quick-start.md
      - Type hints: usage/basic/type-hints.md
    - Advanced:
      - Concurrent Requests: usage/advanced/concurrent-requests.md
      - Using Middlewares: usage/advanced/using-middlewares.md
      - Don't Repeat Clients: usage/advanced/dont-repeat-clients.md
      - Proxy Rate Limiting: usage/advanced/proxy-rate-limiting.md
      - Extending Clients: usage/advanced/extending-clients.md
      - Modifying Schemas: usage/advanced/modifying-schemas.md
  - Reference:
    - reference/index.md
    - Invocation:
      - Invocation: reference/invocation/invocation.md
    - Clients:
      - BaseClient: reference/clients/base-client.md
      - CDragonClient: reference/clients/cdragon-client.md
      - DDragonClient: reference/clients/ddragon-client.md
      - MarlonAPIClient: reference/clients/marlon-api-client.md
      - MerakiCDNClient: reference/clients/meraki-cdn-client.md
      - RiotAPIClient: reference/clients/riot-api-client.md
    - Schemas:
      - CDragonSchema: reference/schemas/cdragon-schema.md
      - DDragonSchema: reference/schemas/ddragon-schema.md
      - MarlonAPISchema: reference/schemas/marlon-api-schema.md
      - MerakiCDNSchema: reference/schemas/meraki-cdn-schema.md
      - RiotAPISchema: reference/schemas/riot-api-schema.md
    - Middlewares:
      - cache_middleware: reference/middlewares/cache_middleware.md
      - http_error_middleware: reference/middlewares/http_error_middleware.md
      - json_response_middleware: reference/middlewares/json_response_middleware.md
      - rate_limiter_middleware: reference/middlewares/rate_limiter_middleware.md
    - Caches:
      - BaseCache: reference/caches/base-cache.md
      - DiskCache: reference/caches/disk-cache.md
      - MemoryCache: reference/caches/memory-cache.md
    - RateLimiters:
      - BaseRateLimiter: reference/ratelimiters/base-rate-limiter.md
      - RiotAPIRateLimiter: reference/ratelimiters/riot-api-rate-limiter.md
    - Utilities:
      - async_to_sync: reference/utilities/async_to_sync.md
      - sync_to_async: reference/utilities/sync_to_async.md
      - TaskGroup: reference/utilities/task-group.md
  - Changelog:
    - v2.0: changelog/v2.0.md
    - v1.2: changelog/v1.2.md
    - v1.1: changelog/v1.1.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 5
          line_length: 70
          members_order: "source"
          show_category_heading: true
          show_if_no_docstring: true
          show_signature_annotations: true
          separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
