# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Types Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Modify package
      run: |
        (cd pulsefire && ls | grep -xv "schemas.py|__init__.py" | xargs rm)
        sed -i -e '2i> **⚠: This package contains schema typings only!**\' README.md
        sed -i 's/name="pulsefire"/name="pulsefire-types"/g' setup.py
        sed -i 's/name="install_requires=install_requires"/name="install_requires=[]"/g' setup.py
        sed -i 's/name="extras_require=extras_require"/name="extras_require={}"/g' setup.py
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
