
name: Run Python tests schemas

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  schedule:
    - cron: "0 12 2 * *"

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'diskcache>=5.6' 'pytest>=8.3' 'typeguard>=4.2'
    - name: Run Python tests
      run: pytest
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        TFT_API_KEY: ${{ secrets.TFT_API_KEY }}
        LOR_API_KEY: ${{ secrets.LOR_API_KEY }}
        PYOT_DEV_KEY: ${{ secrets.PYOT_DEV_KEY }}
